### ISSUE TITLE
How to check if a variable is a Maybe?

### ISSUE THREAD

**Issue by brycehanscomb** [cwmyers/monet.js#109]
If I have a variable that may or may not be a Monet Maybe, how can I check for this?

I tried this:
```js
Maybe.Just(1) instanceof Maybe
// Uncaught TypeError: Right-hand side of 'instanceof' is not callable
``` 
Is there a correct way to do this check?

**Comment by ulfryk** [comment]
Currently `Maybe` is not a constructor of `Maybe` type :(

Simple hack may help here:

```javascript
Maybe.Just(1) instance of Maybe.fn.init
```

or some feature check like:

```javascript
var x = Maybe.Just(1)
if (x && x.isSome && x.isNone && (x.isSome() | x.isNone()) {
 // …
}
```

**Comment by ulfryk** [comment]
@brycehanscomb Don't know if my answer satisfies you… Anyway I've added #111 so when implemented there will be no more doubts ;)

**Comment by brycehanscomb** [comment]
The proposal in #111 looks good. 👍  from me.

Thanks for being responsive, Monet is a great lib!
