### ISSUE TITLE
Maybe.equals returns Maybe in case of two Some's, bool otherwise.

### ISSUE THREAD

**Issue by getOfMyLawn** [cwmyers/monet.js#118]
```
Maybe.None().equals(Maybe.None()) -> true
Maybe.None().equals(Maybe.Some(1)) -> false
Maybe.Some(1).equals(Maybe.None()) -> false
Maybe.Some(1).equals(Maybe.Some(1)) -> Some(true)
Maybe.Some(1).equals(Maybe.Some(2)) -> Some(false)
```
The declared return value for `equals` is `boolean`:
```
interface IEquals<A> {
  equals(a: A): boolean
}
```
Which `Maybe` extends:
```
interface Maybe<T> extends IMonad<T>, IEquals<Maybe<T>>
```

**Comment by ulfryk** [comment]
@getOfMyLawn  - which version of monet do you use? `0.8.10` or `0.9.0-alpha.2` ?

**Comment by getOfMyLawn** [comment]
@ulfryk, `0.9.0-alpha.2`

**Comment by ulfryk** [comment]
on current develop branch it seems to be fixed, so probably the problem will disappear with `0.9.0-alpha.3` release (it's coming soon) :)

**Comment by getOfMyLawn** [comment]
@ulfryk, indeed, develop branch has this issue fixed.
