### ISSUE TITLE
Reader.of question

### ISSUE THREAD

**Issue by raine** [cwmyers/monet.js#19]
I'm just getting into monads in JS and been playing around with few implementations of Reader and noticed that monet's `Reader.of` expects a function. Some libs can wrap a value directly into the default context. I wonder if there's reason for this inconsistency, or is there simply no standard way to implement `Reader.of`?

Here's [a small example](https://gist.github.com/raine/cb351edaa497ee27dc0b) I came up with in livescript.

**Comment by cwmyers** [comment]
Hi Raine,

Great question.

Readers specifically wrap functions as the Reader is responsible to inject the dependencies and compose other Reader wrapped functions together.  So Reader's can't be constructed with arbitrary values but with functions.  Was the documentation on readers helpful? http://cwmyers.github.io/monet.js/#reader If not let me know how I can improve it.

Chris

**Comment by joneshf** [comment]
You should be able to construct a `Reader` with an arbitrary value. If not, it's not an `Applicative`, nevermind being monadic. The implementation of `of` for `Reader` should be equivalent to `const` modulo wrapping. The current `Reader` implementation does not satisfy the identity laws for monads.

That is, these lines: https://github.com/cwmyers/monet.js/blob/a593a51a7a035fda236788c8bee806e427b1d6aa/src/main/javascript/monet.js#L719-L721 should read

```javascript
Reader.of = function (x) {
  return Reader(function (_) {
    return x;
  };
}; 
```

**Comment by cwmyers** [comment]
You guys are right.  I realised `IO.of` was broken too.  This is great cause I can get rid of `lazySequence` too.

Thanks to you both.
