### ISSUE TITLE
Some questions about differences in IO examples

### ISSUE THREAD

**Issue by yemi** [cwmyers/monet.js#21]
First of all, thanks for a great lib!

I'm trying to rewrite parts of our application using ramda/monet. I was looking through some of your resources when I got a little confused about the IO monad.

In the IO example from the docs there is a `read` and a `write` function, both are IO's of impure functions.

In the `IO.html` example from the examples folder, however, there are a bunch of impure functions that are not wrapped in IO's (e.g. `getText`, `setText`, `setHtml` etc.). 

I know that a function like `getTextForId` only maps `getText` over the returned jQuery object from `getId` which eventually returns an IO, meaning that the impurity is only happening inside of the IO.

So to my question: is it okay to define impure functions as long as they're only being used inside an IO or why are the examples in the docs different form the `IO.html` example in this way?

**Comment by cwmyers** [comment]
Yeah, you're right.  That example needs to be reworked.  `getText` etc should all be wrapper in `IO`.

Thanks for the feedback!
