### ISSUE TITLE
React problem with require('monet')

### ISSUE THREAD

**Issue by JoelBMatias** [cwmyers/monet.js#28]
Hi, maybe you can help me. I've developed a backend logic using monads and I was exploring with react.js. Everything goes well until I´ve stared to require the monad module for my backend.
I'm rendering the react on server side, and somehow when I require the monet module I always get a      "Invariant Violation: pp.render(): A valid ReactComponent must be returned.".
I know that the the error is sent by react, but since the problem only happens when a require the monet module, maybe you could know the asnwer. Thanks.

**Comment by cwmyers** [comment]
Were you able to get to the bottom of this?  Unfortunately I don't have any react experience (or time to investigate)

**Comment by ulfryk** [comment]
@JoelBMatias it may be due to `monet` adding some features to prototype of native constructors (like Function). Maybe we can extract all those enhancements to `monet-pimp.js` in next major release? @cwmyers WDYT ?

**Comment by cwmyers** [comment]
Sounds like a good idea.

**Comment by ulfryk** [comment]
@JoelBMatias - try `0.9.0-alpha.2` - should be now fine

**Comment by ulfryk** [comment]
Should have been fixed in #62
