### ISSUE TITLE
Support with async await

### ISSUE THREAD

**Issue by RaviVaranasi** [cwmyers/monet.js#29]
I have been using babel (async await features) along with monet.js to help me write code in declarative style.  I have used the Either monad to represent a success/failure condition. Below is some pseudo code.
```
async function(response) => {
    // return Either monad
    let eitherResult = await generateSessionKey(url);
    eitherResult.map((sessionKey) =>  await callApi(sessionKey))
        .cata((errorResult) => response.status(404).send(errorResult),
                 (success)      => response.sendJson(success));
}
```

This does not work since map function returns immediately and an empty response is written back. Is it possible to have a version of map function that honors Future/Promise values?

**Comment by cwmyers** [comment]
Futures are on their way! Hopefully in version 0.9.0

**Comment by ulfryk** [comment]
Actually Futures will not land in `0.9.0` and probably not in `0.10.0` :(

We strongly suggest usage of https://github.com/fluture-js/Fluture
