### ISSUE TITLE
export to single object in the browser

### ISSUE THREAD

**Issue by charlierudolph** [cwmyers/monet.js#30]
When using in the browser, every monad is added to the window object.

In keeping with the standard for libraries, I believe it should instead only set window.Monet and each type can then be accessed as a property of Monet. 

Similar to how you have `monet-pimp.js` you could have `monet-global.js` which allows people to keep using it in the current fashion.

**Comment by cwmyers** [comment]
That is a very good idea.

On 5 August 2015 at 10:09, Charlie Rudolph <notifications@github.com> wrote:

> When using in the browser, every monad is added to the window object.
>
> In keeping with the standard for libraries, I believe it should instead
> only set window.Monet and each type can then be accessed as a property of
> Monet.
>
> Similar to how you have monet-pimp.js you could have monet-global.js
> which allows people to keep using it in the current fashion.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cwmyers/monet.js/issues/30>.
>



-- 
http://chrisandjo.com

**Comment by ulfryk** [comment]
@charlierudolph @cwmyers - Adding global `monet` or `Monet` object is great idea! 

But removing all stuff from `window` probably shouldn't be done with MINOR version update (0.8.x -> 0.9.x) as it has to keep backward compatibility…

`monet-global.js` is great idea, but I'm not sure if it's enough to `keep backward compatibility`.

What do you say guys (just dispel my doubts and we can do it)?

**Comment by charlierudolph** [comment]
Correct its not backward compatible, if you move the current functionality to monet-global. I believe bumping a minor, prior to 1.0 indicates a breaking change. However I think it would be probably be a good idea to just jump to 1.0

**Comment by ulfryk** [comment]
I'm thinking of some transitional solution for `0.9.0`/`0.10.0` - e.g. If you add some global flag, you'll get all packed into `Monet`, else everything is as now - and when we reach `1.0.0` dropping all global things other than `Monet` object (wit fallback in `monet-global.js`)… WDYT?

**Comment by ulfryk** [comment]
@charlierudolph
Ok, it's done - from `0.9.0-alpha.2` you can `window.useMonetGlobalObject = true` and everything will be assigned to global `Monet` object - no polluting of global scope :)
