### ISSUE TITLE
What am I missing (code as documented simply errors)

### ISSUE THREAD

**Issue by SamMorrowDrums** [cwmyers/monet.js#31]
According to the documentation this should work:

```
Some(2).takeLeft(Some(5))

Uncaught TypeError: some(...).takeLeft is not a function
```
![screen shot 2015-09-24 at 09 17 18](https://cloud.githubusercontent.com/assets/4811358/10068498/ba121902-629c-11e5-9abe-a73416703b7f.png)

http://jsfiddle.net/88k4zzhg/1/

**Comment by cwmyers** [comment]
Hi Sam,

It looks like you are referencing an old version of monet (0.6.6) in your
example. It looks like you are referencing the one used to build the doco
pages. Try referencing the latest one in the repo here:

https://raw.githubusercontent.com/cwmyers/monet.js/master/src/main/javascript/monet.js
https://raw.githubusercontent.com/cwmyers/monet.js/master/src/main/javascript/monet-pimp.js

Good luck and thanks for having a look at monet.js!

Cheers,
Chris

On 24 September 2015 at 18:16, Sam Morrow <notifications@github.com> wrote:

> According to the documentation this should work:
>
> Some(2).takeLeft(Some(5))
>
> Uncaught TypeError: some(...).takeLeft is not a function
>
> [image: screen shot 2015-09-24 at 09 17 18]
> <https://cloud.githubusercontent.com/assets/4811358/10068498/ba121902-629c-11e5-9abe-a73416703b7f.png>
>
> http://jsfiddle.net/88k4zzhg/1/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cwmyers/monet.js/issues/31>.
>



-- 
http://chrisandjo.com

**Comment by SamMorrowDrums** [comment]
Cheers, makes sense. I've got it working, but if it is possible, it would be far better to have the latest versions included in the monet.js homepage. It's a brilliant place to interactively try out the docs.

**Comment by cwmyers** [comment]
Will do



—
