### ISSUE TITLE
Clarification with signature and implementation of bind/flatMap of MonadT

### ISSUE THREAD

**Issue by paulvictor** [cwmyers/monet.js#39]
Hi, Am a new guy to Monad Transformers, so help me clarify if I'm mentioning something wrong, I was looking at the implementation of bind of MonadT ( https://github.com/cwmyers/monet.js/blob/master/src/main/javascript/monet.js#L591-L595 ), and looking at the signature of bind(from https://en.wikibooks.org/wiki/Haskell/Monad_transformers ), isn't it the case that bind should take as argument, a function which takes an A => MonadT[B] ?
```
(>>=) :: MaybeT m a -> (a -> MaybeT m b) -> MaybeT m b
```
The spec given https://github.com/cwmyers/monet.js/blob/ebdffd1bf64d26b00f75bf01490720256eb70396/src/test/javascript/monad_transformer_spec.js#L28-L31  also is a function which flatMap's over the inner Monad, without considering the outer monad. Am I getting something wrong? Help clarify?

**Comment by cwmyers** [comment]
The monad transformer in monet is undocumented and I'm unhappy with the implementation.  It will be removed in the next version.  In the future there will be specific transformers such as MaybeT, EitherT etc.
