### ISSUE TITLE
Please publish 0.8.7 to NPM

### ISSUE THREAD

**Issue by ulfryk** [cwmyers/monet.js#40]
…`Maybe.cata()` is truly useful :+1:

**Comment by cwmyers** [comment]
I published it last week. Are you not seeing it?

**Comment by ulfryk** [comment]
Latest on Bower is `0.8.7` but on [NPM](https://www.npmjs.com/package/monet) it's `0.8.6`.

<img width="300" alt="screen shot 2016-02-06 at 22 13 57" src="https://cloud.githubusercontent.com/assets/1754948/12869413/16210f72-cd1f-11e5-8a51-6a20edf6cf6b.png">

**Comment by cwmyers** [comment]
So sorry about that.  It should be there now.  Not sure what I did wrong last week!

Thanks for your patience.

Chris

**Comment by ulfryk** [comment]
@cwmyers - thank you vary much. Keep the good work!
