### ISSUE TITLE
node v5.7.1 ReferenceError: Either is not defined

### ISSUE THREAD

**Issue by StasKoval** [cwmyers/monet.js#46]
`
const monet = require('monet');

let nn = Either.Right('Dulwich, London');

`
and then 
`
let nn = Either.Right('Dulwich, London');
 ReferenceError: Either is not defined
`

**Comment by StasKoval** [comment]
Oh.. 
const Maybe = require('monet').Maybe;

**Comment by ulfryk** [comment]
@StasKoval - can we close this issue ? :)

**Comment by ulfryk** [comment]
@StasKoval @cwmyers - closing this one as it's probably not an issue.
