### ISSUE TITLE
Fix bower.json

### ISSUE THREAD

**Issue by ulfryk** [cwmyers/monet.js#51]
`invalid-meta The "main" field has to contain only 1 file per filetype; found multiple .js files: ["src/main/javascript/monet.js","src/main/javascript/monet-pimp.js"]`

**Comment by Codermar** [comment]
Any work around this for the time being? I don't have a problem running locally but the maven front-end plugin and Jenkins report it as error :-( ...

**Comment by ulfryk** [comment]
Should be fixed with new release -> https://github.com/cwmyers/monet.js/releases/tag/v0.8.10

@Codermar - can you confirm ?

**Comment by Codermar** [comment]
I am not sure I can confirm this. I am not using monet.js directly and when searching in my bower_components directory I don't see any dependencies there. I thought this was a bower specific issue but it is maybe a package specific issue (in my case it was angular-datatables) Let me know if there's any other way I can help verify it.

**Comment by ulfryk** [comment]
@Codermar - I got it. I've misunderstood you before - sadly I do not know any work around :(

Anyway - I've checked and no more problems with this error in monet :)
