### ISSUE TITLE
Minified version

### ISSUE THREAD

**Issue by eunikolsky** [cwmyers/monet.js#59]
Hi @cwmyers.
I created a PR to add `monet.js` to https://www.jsdelivr.com/: https://github.com/jsdelivr/jsdelivr/pull/11351. And they prefer a minified version. Are you planning to upload that as well?
Thanks.

**Comment by ulfryk** [comment]
@eunikolsky - We'll deliver minified version with `0.9.0` :)

**Comment by ulfryk** [comment]
....workin on it #63

**Comment by ulfryk** [comment]
@eunikolsky - you can now try `0.9.0-alpha.2` - it should work without any errors and provides minified version.
