### ISSUE TITLE
Human-readable string representation

### ISSUE THREAD

**Issue by WojciechP** [cwmyers/monet.js#60]
Hello,
I think it would be nice to have proper string representation of monet data types in terms of `.toString()` / `.inspect()` methods. In particular, I think these constructs should represent themselves:

- `Just(1)`
- `Left(2)`
- `Right(3)`
- `Success(4)`
- `Fail(5)`
- `Identity(6)`

Moreover, I'd represent `Nothing()`, `List.fromArray([1, 2, 3])` and `NEL.fromArray([1, 2, 3])` as `Nothing`, `List(1, 2, 3)` and `NEL(1, 2, 3)`, respectively.

I'd happily contribute, but I'd rather hear your opinion first. @cwmyers, @ulfryk  - what do you think?

**Comment by cwmyers** [comment]
Thanks for doing this. It's great.

**Comment by ulfryk** [comment]
@WojciechP - can it be closed (as DONE) now ?

**Comment by WojciechP** [comment]
Sure :)
