### ISSUE TITLE
Maybe.Some bind returning an Either Monad

### ISSUE THREAD

**Issue by efrister** [cwmyers/monet.js#65]
Hi

I was playing around with monet and found it pretty exciting. However, there's an issue I have when I want to return a different Monad inside a `bind` than the "outer" Monad. 

**Example:**
Assume that I have a `Maybe` Monad (`Some` or `None`), and I want to `bind` a function that returns an `Either` (`Left` or `Right`), depending on some contrived condition:

```
aMaybe.bind(function(val){
    if (val.length == 0) {
        return Either.Left("Empty string");
    } else {
        return Either.Right(val);
    }
})
```

If the `Maybe` is `Some`, then I'll actually get an `Either` back. However, if the `Maybe` is `None`, I'll stay in the `Maybe` Monad as the `bind` is not evaluated.

I'm pretty sure this is not allowed; i.e. by convention the `bind` should probably return the same Monad type as the "current" Monad. However, how should I then handle situations where I actually would like to execute code inside a `bind` that would make sense to return an `Either`? How would one actually go about solving such an issue with Monet?

Sorry if this is common knowledge when working with Monads a lot. It's a new topic for me and I want to make sure I do the right thing. If there happen to be resources about this, I'd be happy even if you just reply with a one-line link to the answer.

**Comment by cwmyers** [comment]
Hi Erik,

You are required to return a Some or a None inside the bind for Maybe.
It's signature is Maybe[A].bind(a => Maybe[B]).  So returning an Either in
a bind is illegal. Monads in general don't compose with each other.  If
seems like you want to either use fold or cata for what you want to do.

Hope this helps,
Chris

**Comment by efrister** [comment]
Thanks. That makes sense.
