### ISSUE TITLE
illegal state exception on Maybe.ap() invocation with null returning function

### ISSUE THREAD

**Issue by olivr70** [cwmyers/monet.js#66]
hello

I am really new to the monad universe, and in fact using Monet.js to explore it.

I stumbled on an "Illegal state exception" while running 

``` Javascript
function nullFunc() { return null }
Some("a").ap(Some(nullFunc)); // throws "Illegal state exception" from Maybe.fn.Maybe.init
```
The problem seems to come from the fact that the **map** function listed hereafter composer ***this.of*** with **fn** (my nullFunc).

Looking though the spec I did not see any requirement that ap() should be passed a non-null returning function. Did I miss something 

Why use **this.of** and not **this.fromNull** in **map** ?

```
var map = function (fn) {
        return this.bind(this.of.compose(fn))
    }
```

Sorry I didn't proposed the PR, but I have miles to cover and the subject before

**Comment by ulfryk** [comment]
It is proper behaviour actually -- see discussion here: https://github.com/cwmyers/monet.js/issues/53
