### ISSUE TITLE
Maybe.foreach method

### ISSUE THREAD

**Issue by dsschwarz** [cwmyers/monet.js#67]
Hi, I recently started using this great library. I ran into an issue when trying to do some logic like

```
if (maybe.isSome) doThing(maybe.some())
```

The map method would be elegant, but throws on functions that return undefined. I'd like to add a foreach method to the basic monad type, with a signature like

```
foreach(fn: (val: T) => void): void
```

Before I go ahead with implementing that - is this something that would be beneficial?

**Comment by cwmyers** [comment]
That would be awesome! I'm surprised it wasn't already there. Oops!

**Comment by ulfryk** [comment]
Yeah, `maybe.cata(() => IO(() => {}), value => IO(() => doThing(value))).run()` seems to be an overkill…

👍 

The only thing is that JS world uses rather `forEach` then `foreach` ;)

**Comment by ulfryk** [comment]
@dsschwarz - please see #78

**Comment by ulfryk** [comment]
@dsschwarz - done in #95

I'll release `0.9.0-alpha.3`soon :)
