### ISSUE TITLE
Function.prototype extensions

### ISSUE THREAD

**Issue by Andarist** [cwmyers/monet.js#68]
Shouldn't they be an opt-in by using `monet-pimp`? Polluting native objects shouldnt be made by default in my opinion. Its just asking for trouble, especially in my use case when I do not have full control about environment my script is working in.

**Comment by ulfryk** [comment]
@Andarist - we're working on it for https://github.com/cwmyers/monet.js/milestone/3

**Comment by Andarist** [comment]
Good to hear!
