### ISSUE TITLE
Maybe.fromFalsy operator

### ISSUE THREAD

**Issue by kpudlik** [cwmyers/monet.js#73]
Hello,

I've noticed that `Maybe.fromNull(val)` works only for null or non-null values. In my case I wanted to check whether value is an empty string (perform some mappings etc.) or not (just return another value). The most elegant way of doing this is to use `.filter`:
`Maybe.fromNull('').filter(Boolean)`.

My suggestion is to make an additional operator like `Maybe.fromFalsy(val)` which checks falsy values:

```
Maybe.fromFalsy('')
    .map(val => val.concat('X'))
    .orJust('ElseString') // 'ElseString'
```

**Comment by ulfryk** [comment]
@kpudlik - please see #78
