### ISSUE TITLE
Maybe.contains?

### ISSUE THREAD

**Issue by emmanueltouzery** [cwmyers/monet.js#88]
Would you accept a PR adding:

    Maybe<T>.contains(T) => boolean

it can be coded as `maybe.filter(x => x === value).isDefined()` but when you get to more complicated things, it seems to me that every little conciseness helps.

**Comment by ulfryk** [comment]
Great idea, but _Maybe_ you would like to implement `.contains(val: T): boolean` on all types that it fits to? It means:

- Identity
- Maybe 
- Either (treat Left as empty)
- Validation (treat Fail as empty)
- List
- NEL

And maybe also these operators:

- `.isEmpty(): boolean` (this will be helpful for `contains` and all below)
- `.every(fn: (v: T) => boolean): boolean`  - ( see scala Option `forall` )
 - returns `true` if owner is empty
- `.exists(fn: (v: T) => boolean): boolean` ( like js Array `.some()` )
  - returns `false` if owner is empty

What do you say?

**Comment by emmanueltouzery** [comment]
Well adding contains is a small task, adding all that not anymore ;-)
But i agree about adding contains in more types. I'll see when i can manage.

**Comment by ulfryk** [comment]
#93 fixed this issue
