### ISSUE TITLE
side-effecting actions?

### ISSUE THREAD

**Issue by emmanueltouzery** [cwmyers/monet.js#92]
what do you think about adding side-effecting functions like:

```
List<T>.forEach: (T=>void) => void
Maybe.forEach(T=>void) => void
```

same for non empty list and so on. For ˙Maybe` we could name it `ifPresent` instead of `forEach`?

**Comment by emmanueltouzery** [comment]
aha I see you have `List.each` for that purpose already. Then I would add `Maybe.each`, or `Maybe.ifPresent`.

**Comment by ulfryk** [comment]
I think that it would be great to use `forEach` and deprecate `each`. And add it to to `Identity`, `Maybe`, `Either`, `List`, `NEL` and `Validation`.

I'm also thinking about some left side representatives for at least `Either` and `Validation`, like `forEachLeft` and `forEachFail`, WDYT @emmanueltouzery  ?

**Comment by emmanueltouzery** [comment]
No issues for the left-side, the only question is naming.

Options: `orElseRun()`, or `ifLeft`/`ifFailed`. But `forEachLeft` and `forEachFail` may be more discoverable (if arguably less readable).

**Comment by ulfryk** [comment]
I really like `orElseRun()` but for `Maybe` :+1:

`ifLeft` / `ifFail` are quite readable but seem to be inconsistent with common JS `forEach` interface. 

I still think that `forEach(Left|Fail)` are consistent..

**Comment by emmanueltouzery** [comment]
hmm another option maybe... have them return this instead of void? so you can chain for instance...

    maybe.forEach(...).orElseRun(...)

I just saw that bug related to that =>
https://github.com/javaslang/javaslang/issues/1781

for instance javaslang also has besides `forEach`, `peek` which also returns this, allowing chaining. So do we have all these overloads return this? If we don't then we need two lines:

    maybe.forEach(...)
    maybe.orElseRun(...)

**Comment by ulfryk** [comment]
Common `forEach` return type across existing stuff is `void` and as side effects should be the last thing done maybe it's better to leave it that way. If one needs side effect for `Some` - there is `forEach`, for `None` there is `orElseRun` and if both sides need a callback, then `.cata` is the answer. And same with `Either` and `Validation`.

**Comment by emmanueltouzery** [comment]
good point about `cata`! that sorts it out then.

**Comment by ulfryk** [comment]
#95 fixed this issue
